on:
  workflow_dispatch:
  push:
    branches:
      - main
      - github-actions

name: fox32asm Unstable - Linux

jobs:
  fox32asm-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fox32asm
          path: target/release/fox32asm
